/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ClientProfileRouteImport } from './routes/client.profile'
import { Route as ClientBookRouteImport } from './routes/client.book'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AdminMapRouteImport } from './routes/admin.map'
import { Route as ClientBookingsIndexRouteImport } from './routes/client.bookings.index'
import { Route as ClientBookingsIdRouteImport } from './routes/client.bookings.$id'
import { Route as AdminJobsIdRouteImport } from './routes/admin.jobs.$id'

const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientRoute,
} as any)
const ClientBookRoute = ClientBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => ClientRoute,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AdminRoute,
} as any)
const ClientBookingsIndexRoute = ClientBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => ClientRoute,
} as any)
const ClientBookingsIdRoute = ClientBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => ClientRoute,
} as any)
const AdminJobsIdRoute = AdminJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/client': typeof ClientRouteWithChildren
  '/admin/map': typeof AdminMapRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/client/book': typeof ClientBookRoute
  '/client/profile': typeof ClientProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/admin/jobs/$id': typeof AdminJobsIdRoute
  '/client/bookings/$id': typeof ClientBookingsIdRoute
  '/client/bookings/': typeof ClientBookingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/client/book': typeof ClientBookRoute
  '/client/profile': typeof ClientProfileRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/admin/jobs/$id': typeof AdminJobsIdRoute
  '/client/bookings/$id': typeof ClientBookingsIdRoute
  '/client/bookings': typeof ClientBookingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/client': typeof ClientRouteWithChildren
  '/admin/map': typeof AdminMapRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/client/book': typeof ClientBookRoute
  '/client/profile': typeof ClientProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/admin/jobs/$id': typeof AdminJobsIdRoute
  '/client/bookings/$id': typeof ClientBookingsIdRoute
  '/client/bookings/': typeof ClientBookingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/client'
    | '/admin/map'
    | '/admin/teams'
    | '/client/book'
    | '/client/profile'
    | '/admin/'
    | '/client/'
    | '/admin/jobs/$id'
    | '/client/bookings/$id'
    | '/client/bookings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/map'
    | '/admin/teams'
    | '/client/book'
    | '/client/profile'
    | '/admin'
    | '/client'
    | '/admin/jobs/$id'
    | '/client/bookings/$id'
    | '/client/bookings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/client'
    | '/admin/map'
    | '/admin/teams'
    | '/client/book'
    | '/client/profile'
    | '/admin/'
    | '/client/'
    | '/admin/jobs/$id'
    | '/client/bookings/$id'
    | '/client/bookings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClientRoute: typeof ClientRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/profile': {
      id: '/client/profile'
      path: '/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/book': {
      id: '/client/book'
      path: '/book'
      fullPath: '/client/book'
      preLoaderRoute: typeof ClientBookRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/bookings/': {
      id: '/client/bookings/'
      path: '/bookings'
      fullPath: '/client/bookings/'
      preLoaderRoute: typeof ClientBookingsIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/bookings/$id': {
      id: '/client/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/client/bookings/$id'
      preLoaderRoute: typeof ClientBookingsIdRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/jobs/$id': {
      id: '/admin/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/admin/jobs/$id'
      preLoaderRoute: typeof AdminJobsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminMapRoute: typeof AdminMapRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminJobsIdRoute: typeof AdminJobsIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMapRoute: AdminMapRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminJobsIdRoute: AdminJobsIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientBookRoute: typeof ClientBookRoute
  ClientProfileRoute: typeof ClientProfileRoute
  ClientIndexRoute: typeof ClientIndexRoute
  ClientBookingsIdRoute: typeof ClientBookingsIdRoute
  ClientBookingsIndexRoute: typeof ClientBookingsIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientBookRoute: ClientBookRoute,
  ClientProfileRoute: ClientProfileRoute,
  ClientIndexRoute: ClientIndexRoute,
  ClientBookingsIdRoute: ClientBookingsIdRoute,
  ClientBookingsIndexRoute: ClientBookingsIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ClientRoute: ClientRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
